### ISSUE TITLE
vagrant up jenkins setup failed

### ISSUE THREAD

**Issue by nddmars** [rapid7/metasploitable3#110]
## Issue Description
Hi

I am setting up metasploitable3 manually instead of powershell and  during the last command "vagrant up" , I noticed the following error. I have tried installing manuall but ending up with same error. 
I am following default windows_2008_r2.json setup. Please find below log.

## Host System
* OS:windows 10 x64
* Packer Version:0.12.3
* Vagrant Version:1.9.0
* VirtualBox Version: 5.1.18

## Command Output
vagrant up 

> default: C:\Windows\system32>"C:\Program Files\jenkins\jenkins.exe" -Service Install
==> default: This version of C:\Program Files\jenkins\jenkins.exe is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.
==> default:
==> default:
==> default: C:\Windows\system32>sc config jenkins start= auto
==> default: [SC] OpenService FAILED 1060:
==> default:
==> default:
==> default: The specified service does not exist as an installed service.
The following WinRM command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

**Comment by Soulence** [comment]
I suggest upgrading to vagrant 1.9.2. this resolved all my vagrant issues. DO NOT USE 1.9.3 this caused additional issues.

**Comment by nddmars** [comment]
I will try that out. But point to note is I got the same error when I tried jenkins command manually.

**Comment by Chan9390** [comment]
Hey @nddmars what do you mean by `I have tried installing manuall but ending up with same error`. Are you installing it on a virtual machine (***with Windows Server 2008 r2 as guest OS*** ) or on some other OS ?

**Comment by edmtorres02** [comment]
I encountered this same error, VM has Windows Server 2008 R2 as guest OS.

**Comment by Chan9390** [comment]
@edmtorres02 Did you manually download the iso file ? Can you paste the sha256 and md5 checksum of the iso file you downloaded ?

**Comment by edmtorres02** [comment]
iso file? of my Windows 2008 R2 installer?

**Comment by Chan9390** [comment]
Can I know how you setup metasploitable 3 ?

**Comment by edmtorres02** [comment]
Host OS is Kali. I installed Packer, Vagrant, Vagrant-plugin, and Virtual Box. Clone the metasploitable3 folder and then copy **en_windows_server_2008_r2_with_sp1_vl_build_x64_dvd_617403.iso** to the **\metasploitable3\iso** folder. Run the **build_win2008.sh**.

**Comment by Chan9390** [comment]
Maybe jenkins is not compatible with that version of Windows Server. Try downloading windows server from [here](http://download.microsoft.com/download/7/5/E/75EC4E54-5B02-42D6-8879-D8D3A25FBEF7/7601.17514.101119-1850_x64fre_server_eval_en-us-GRMSXEVAL_EN_DVD.iso) and place it in the metasploitable3\iso folder

**Comment by edmtorres02** [comment]
@Chan9390 I tied using the iso from the link u gave me, I got past thru this error (jenkins) but got stuck with elastic search error issue #157 

Attached is the log file.
[log170708.txt](https://github.com/rapid7/metasploitable3/files/1133109/log170708.txt)

**Comment by Chan9390** [comment]
There were a few errors. Again jdk8 was not installed.

Error 1:
```
    virtualbox-iso: The term ':PACKER_BUILDER_TYPE=virtualbox-iso' is not recognized as the name of
    virtualbox-iso: a cmdlet, function, script file, or operable program. Check the spelling of th
    virtualbox-iso: e name, or if a path was included, verify that the path is correct and try agai
    virtualbox-iso: n.
    virtualbox-iso: At line:1 char:42
    virtualbox-iso: + & { :PACKER_BUILDER_TYPE="virtualbox-iso" <<<< ; :PACKER_BUILD_NAME="virtualb
    virtualbox-iso: ox-iso"; c:/Windows/Temp/script.ps1; exit }
    virtualbox-iso: + CategoryInfo          : ObjectNotFound: (:PACKER_BUILDER_TYPE=virtualbox
    virtualbox-iso: -iso:String) [], CommandNotFoundException
    virtualbox-iso: + FullyQualifiedErrorId : CommandNotFoundException
    virtualbox-iso:
    virtualbox-iso: The term ':PACKER_BUILD_NAME=virtualbox-iso' is not recognized as the name of a
    virtualbox-iso: cmdlet, function, script file, or operable program. Check the spelling of the
    virtualbox-iso: name, or if a path was included, verify that the path is correct and try again.
    virtualbox-iso: At line:1 char:79
    virtualbox-iso: + & { :PACKER_BUILDER_TYPE="virtualbox-iso"; :PACKER_BUILD_NAME="virtualbox-iso
    virtualbox-iso: " <<<< ; c:/Windows/Temp/script.ps1; exit }
    virtualbox-iso: + CategoryInfo          : ObjectNotFound: (:PACKER_BUILD_NAME=virtualbox-i
    virtualbox-iso: so:String) [], CommandNotFoundException
    virtualbox-iso: + FullyQualifiedErrorId : CommandNotFoundException
    virtualbox-iso:
```

Error 2:
```
    virtualbox-iso: C:\Users\vagrant>choco install tomcat --version 8.0.33
    virtualbox-iso: Chocolatey v0.10.7
    virtualbox-iso: Installing the following packages:
    virtualbox-iso: tomcat
    virtualbox-iso: By installing you accept licenses for the packages.
    virtualbox-iso: Progress: Downloading jdk8 8.0.131... 100%
    virtualbox-iso: Progress: Downloading Tomcat 8.0.33... 100%
    virtualbox-iso:
    virtualbox-iso: jdk8 v8.0.131 [Approved]
    virtualbox-iso: jdk8 package files install completed. Performing other installation steps.
    virtualbox-iso: Downloading JDK from http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-windows-x64.exe
    virtualbox-iso: Installing jdk8...
    virtualbox-iso: ERROR: Running ["C:\ProgramData\chocolatey\lib\jdk8\tools\jdk-8u131-windows-x64.exe" /s STATIC=1 ADDLOCAL="ToolsFeature,SourceFeature" ] was not successful. Exit code was '1603'. See log for possible error messages.
    virtualbox-iso: The install of jdk8 was NOT successful.
    virtualbox-iso: Error while running 'C:\ProgramData\chocolatey\lib\jdk8\tools\chocolateyInstall.ps1'.
    virtualbox-iso: See log for details.
```

Error 3 (includes 2nd also):
```
    virtualbox-iso: Failures
    virtualbox-iso: - jdk8 (exited 1603) - Error while running 'C:\ProgramData\c
hocolatey\lib\jdk8\tools\chocolateyInstall.ps1'.
    virtualbox-iso: See log for details.
    virtualbox-iso: - tomcat (exited -1) - Error while running 'C:\ProgramData\c
hocolatey\lib\Tomcat\tools\chocolateyInstall.ps1'.
    virtualbox-iso: See log for details.
```

Error 4:
```
    virtualbox-iso: C:\Users\vagrant>powershell -File "C:\Program Files\wordpres
s\update_ip.ps1"
    virtualbox-iso: Cannot index into a null array.
    virtualbox-iso: At C:\Program Files\wordpress\update_ip.ps1:2 char:28
    virtualbox-iso: + $ipaddr = $ip[0].ipaddress[ <<<< 0]
    virtualbox-iso: + CategoryInfo          : InvalidOperation: (0:Int32) [], Ru
ntimeException
    virtualbox-iso: + FullyQualifiedErrorId : NullArray
    virtualbox-iso:
    virtualbox-iso: Updating Wordpress IP to
```

Error 5:
```
    virtualbox-iso: C:\Users\vagrant>powershell -Command "$req = [System.Net.HttpWebRequest]::Create('http://localhost:9200/metasploitable3/'); $req.method = 'P
UT'; $req.GetResponse()"
    virtualbox-iso: Exception calling "GetResponse" with "0" argument(s): "Unable to connect to the
    virtualbox-iso: remote server"
    virtualbox-iso: At line:1 char:124
    virtualbox-iso: + $req = [System.Net.HttpWebRequest]::Create('http://localho...skipping 23 lines
    virtualbox-iso: pWebRequest]::Create('http://localhost:9200/metasploitable3/
message/1'); $req.m
    virtualbox-iso: ethod = 'PUT'; $req.ContentType = 'application/x-www-form-urlencoded'; $stream
    virtualbox-iso: = $req.GetRequestStream(); $stream.Write <<<< ($body, 0, $body.Length); $stream
    virtualbox-iso: .close(); $req.GetResponse()
    virtualbox-iso: + CategoryInfo          : InvalidOperation: (Write:String) [], RuntimeExce
    virtualbox-iso: ption
    virtualbox-iso: + FullyQualifiedErrorId : InvokeMethodOnNull
    virtualbox-iso:
    virtualbox-iso: You cannot call a method on a null-valued expression.
    virtualbox-iso: At line:1 char:394
    virtualbox-iso: + $body = [System.Text.Encoding]::ASCII.GetBytes('{"user":"kimchy", "post_date"
    virtualbox-iso: : "2009-11-15T14:12:12", "message": "Elasticsearch" }'); $req = [System.Net.Htt
    virtualbox-iso: pWebRequest]::Create('http://localhost:9200/metasploitable3/message/1'); $req.m
    virtualbox-iso: ethod = 'PUT'; $req.ContentType = 'application/x-www-form-urlencoded'; $stream
    virtualbox-iso: = $req.GetRequestStream(); $stream.Write($body, 0, $body.Length); $stream.close
    virtualbox-iso: <<<< (); $req.GetResponse()
    virtualbox-iso: + CategoryInfo          : InvalidOperation: (close:String) [], RuntimeExce
    virtualbox-iso: ption
    virtualbox-iso: + FullyQualifiedErrorId : InvokeMethodOnNull
    virtualbox-iso:
    virtualbox-iso: Exception calling "GetResponse" with "0" argument(s): "Unable to connect to the
    virtualbox-iso: remote server"
    virtualbox-iso: At line:1 char:414
    virtualbox-iso: + $body = [System.Text.Encoding]::ASCII.GetBytes('{"user":"kimchy", "post_date"
    virtualbox-iso: : "2009-11-15T14:12:12", "message": "Elasticsearch" }'); $req = [System.Net.Htt
    virtualbox-iso: pWebRequest]::Create('http://localhost:9200/metasploitable3/message/1'); $req.m
    virtualbox-iso: ethod = 'PUT'; $req.ContentType = 'application/x-www-form-urlencoded'; $stream
    virtualbox-iso: = $req.GetRequestStream(); $stream.Write($body, 0, $body.Length); $stream.close
    virtualbox-iso: + FullyQualifiedErrorId : DotNetMethodException
```
