### ISSUE TITLE
Unable to build environment

### ISSUE THREAD

**Issue by Maho42** [rapid7/metasploitable3#313]
## Issue Description
Note that I am using the VMware provisioner: I've been working on this the last few days and it seems to fail at a different point each time (the first time was a similar error around 7zip and not having the installer).

Command run: packer build --only=vmware-iso ./packer/templates/windows_2008_r2.json

## Host System
* OS: macOS High Sierra 10.13.15
* Packer Version: Packer v1.2.4
* Vagrant Version: Installed Version: 2.1.2
* VMWare Version: Fusion Professional 10.1.2

## Command Output
```
==> vmware-iso: Provisioning with shell script: /Users/maho/Library/Lab/metasploitable3/packer/templates/../../scripts/installs/install_elasticsearch.bat
    vmware-iso:
    vmware-iso: C:\Users\vagrant>powershell -Command "(New-Object System.Net.WebClient).DownloadFile('http://repo1.maven.org/maven2/org/elasticsearch/elasticsearch/1.1.1/elasticsearch-1.1.1.zip', 'C:\Windows\Temp\elasticsearch-1.1.1.zip')"  0<NUL
    vmware-iso:
    vmware-iso: C:\Users\vagrant>cmd /c ""C:\Program Files\7-Zip\7z.exe" x "C:\Windows\Temp\elasticsearch-1.1.1.zip" -o"C:\Program Files\""
    vmware-iso:
    vmware-iso: 7-Zip 18.05 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2018-04-30
    vmware-iso:
    vmware-iso: Scanning the drive for archives:
    vmware-iso: 1 file, 22608755 bytes (22 MiB)
    vmware-iso:
    vmware-iso: Extracting archive: C:\Windows\Temp\elasticsearch-1.1.1.zip
    vmware-iso: --
    vmware-iso: Path = C:\Windows\Temp\elasticsearch-1.1.1.zip
    vmware-iso: Type = zip
    vmware-iso: Physical Size = 22608755
    vmware-iso:
    vmware-iso: Everything is Ok
    vmware-iso:
    vmware-iso: Folders: 5
    vmware-iso: Files: 48
    vmware-iso: Size:       25590291
    vmware-iso: Compressed: 22608755
    vmware-iso:
    vmware-iso: C:\Users\vagrant>cmd /c ""C:\Program Files\elasticsearch-1.1.1\bin\service.bat" install"
    vmware-iso: JAVA_HOME environment variable must be set!
    vmware-iso: Press any key to continue . . .
    vmware-iso:
    vmware-iso: C:\Users\vagrant>sc config "elasticsearch-service-x64" start= auto
    vmware-iso: [SC] OpenService FAILED 1060:
    vmware-iso:
    vmware-iso: The specified service does not exist as an installed service.
    vmware-iso:
    vmware-iso:
    vmware-iso: C:\Users\vagrant>cmd /c ""C:\Program Files\elasticsearch-1.1.1\bin\service.bat" start"
    vmware-iso: JAVA_HOME environment variable must be set!
    vmware-iso: Press any key to continue . . .
    vmware-iso:
    vmware-iso: C:\Users\vagrant>powershell -Command "Start-Sleep -s 30"
    vmware-iso:
    vmware-iso: C:\Users\vagrant>powershell -Command "$req = [System.Net.HttpWebRequest]::Create('http://localhost:9200/metasploitable3/'); $req.method = 'PUT'; $req.GetResponse()"
    vmware-iso: Exception calling "GetResponse" with "0" argument(s): "Unable to connect to
    vmware-iso: the remote server"
    vmware-iso: At line:1 char:108
    vmware-iso: + ... host:9200/metasploitable3/'); $req.method = 'PUT'; $req.GetResponse()
    vmware-iso: +                                                        ~~~~~~~~~~~~~~~~~~
    vmware-iso:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    vmware-iso:     + FullyQualifiedErrorId : WebException
    vmware-iso:
    vmware-iso:
    vmware-iso: C:\Users\vagrant>powershell -Command "$body = [System.Text.Encoding]::ASCII.GetBytes('{\"user\":\"kimchy\", \"post_date\": \"2009-11-15T14:12:12\", \"message\": \"Elasticsearch\" }'); $req = [System.Net.HttpWebRequest]::Create('http://localhost:9200/metasploitable3/message/1'); $req.method = 'PUT'; $req.ContentType = 'application/x-www-form-urlencoded'; $stream = $req.GetRequestStream(); $stream.Write($body, 0, $body.Length); $stream.close(); $req.GetResponse()"
    vmware-iso: Exception calling "GetRequestStream" with "0" argument(s): "Unable to connect
    vmware-iso: to the remote server"
    vmware-iso: At line:1 char:307
    vmware-iso: + ... ion/x-www-form-urlencoded'; $stream = $req.GetRequestStream(); $strea ...
    vmware-iso: +                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    vmware-iso:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    vmware-iso:     + FullyQualifiedErrorId : WebException
    vmware-iso:
    vmware-iso: You cannot call a method on a null-valued expression.
    vmware-iso: At line:1 char:342
    vmware-iso: + ... req.GetRequestStream(); $stream.Write($body, 0, $body.Length); $strea ...
    vmware-iso: +                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    vmware-iso:     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    vmware-iso:     + FullyQualifiedErrorId : InvokeMethodOnNull
    vmware-iso:
    vmware-iso: You cannot call a method on a null-valued expression.
    vmware-iso: At line:1 char:381
    vmware-iso: + ... eam(); $stream.Write($body, 0, $body.Length); $stream.close(); $req.G ...
    vmware-iso: +                                                   ~~~~~~~~~~~~~~~
    vmware-iso:     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    vmware-iso:     + FullyQualifiedErrorId : InvokeMethodOnNull
    vmware-iso:
    vmware-iso: Exception calling "GetResponse" with "0" argument(s): "You must provide a
    vmware-iso: request body if you set ContentLength>0 or SendChunked==true.  Do this by
    vmware-iso: calling [Begin]GetRequestStream before [Begin]GetResponse."
    vmware-iso: At line:1 char:398
    vmware-iso: + ... am.Write($body, 0, $body.Length); $stream.close(); $req.GetResponse()
    vmware-iso: +                                                        ~~~~~~~~~~~~~~~~~~
    vmware-iso:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    vmware-iso:     + FullyQualifiedErrorId : ProtocolViolationException
    vmware-iso:
==> vmware-iso: Stopping virtual machine...
==> vmware-iso: Deleting output directory...
Build 'vmware-iso' errored: Script exited with non-zero exit status: 1

==> Some builds didn't complete successfully and had errors:
--> vmware-iso: Script exited with non-zero exit status: 1

==> Builds finished but no artifacts were created.
```

**Comment by jmartin-r7** [comment]
Based on what I see in this log you something failed earlier in the setup of the java environment.

I ran a test locally and here is what a valid install would have output, can you provide the java install section?

```
    vmware-iso: C:\Users\vagrant>cmd /c ""C:\Program Files\elasticsearch-1.1.1\bin\service.bat" install"
    vmware-iso: Installing service      :  "elasticsearch-service-x64"
    vmware-iso: Using JAVA_HOME (64-bit):  "C:\Program Files\Java\jdk1.8.0_181"
    vmware-iso: The service 'elasticsearch-service-x64' has been installed.
    vmware-iso:
    vmware-iso: C:\Users\vagrant>sc config "elasticsearch-service-x64" start= auto
    vmware-iso: [SC] ChangeServiceConfig SUCCESS
    vmware-iso:
    vmware-iso: C:\Users\vagrant>cmd /c ""C:\Program Files\elasticsearch-1.1.1\bin\service.bat" start"
    vmware-iso: The service 'elasticsearch-service-x64' has been started
    vmware-iso:
    vmware-iso: C:\Users\vagrant>powershell -Command "Start-Sleep -s 30"
    vmware-iso:
    vmware-iso: C:\Users\vagrant>powershell -Command "$req = [System.Net.HttpWebRequest]::Create('http://localhost:9200/metasploitable3/'); $req.method = 'PUT'; $req.GetResponse()"
    vmware-iso:
    vmware-iso:
    vmware-iso: IsMutuallyAuthenticated : False
    vmware-iso: Cookies                 : {}
    vmware-iso: Headers                 : {Content-Length, Content-Type}
    vmware-iso: SupportsHeaders         : True
    vmware-iso: ContentLength           : 21
    vmware-iso: ContentEncoding         :
    vmware-iso: ContentType             : application/json; charset=UTF-8
    vmware-iso: CharacterSet            : UTF-8
    vmware-iso: Server                  :
    vmware-iso: LastModified            : 7/25/2018 6:56:03 PM
    vmware-iso: StatusCode              : OK
    vmware-iso: StatusDescription       : OK
    vmware-iso: ProtocolVersion         : 1.1
    vmware-iso: ResponseUri             : http://localhost:9200/metasploitable3/
    vmware-iso: Method                  : PUT
    vmware-iso: IsFromCache             : False
```
